In [31]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

In [32]:
# Load the dataset
data = pd.read_csv('../data/modelingData/Hong_Kong_International_Airport.csv')

data

,year,Month,Day,Mean_Windspeed,Wind_Direction,Mean_Tempurature,Humidity,Rainfall,Duration,Color
0,2019,1,1,18.4,360,12.3,65,Trace,0,Green
1,2019,1,2,16.5,350,13.5,65,Trace,0,Green
2,2019,1,3,9.2,360,14.7,77,Trace,0,Green
3,2019,1,4,14.4,320,17.9,84,0.3,0,Green
4,2019,1,5,12.6,320,18.0,89,Trace,0,Green
...,...,...,...,...,...,...,...,...,...,...
1912,2024,3,27,24.5,90,23.3,75,0,0,Green
1913,2024,3,28,11.1,80,24.9,77,0,0,Green
1914,2024,3,29,9.1,260,25.7,77,0,0,Green
1915,2024,3,30,11.1,150,26.8,74,0,0,Green
1916,2024,3,31,19.6,220,28.3,74,0,0,Green

In [33]:
# Data Preprocessing

# Check for null values
null_values = data.isnull()
print("Null Values:")
print(null_values)
print("\nCount of Null Values in Each Column:")
print(null_values.sum())

Null Values:
       year  Month    Day  Mean_Windspeed  Wind_Direction  Mean_Tempurature  \
0     False  False  False           False           False             False
1     False  False  False           False           False             False
2     False  False  False           False           False             False
3     False  False  False           False           False             False
4     False  False  False           False           False             False
...     ...    ...    ...             ...             ...               ...
1912  False  False  False           False           False             False
1913  False  False  False           False           False             False
1914  False  False  False           False           False             False
1915  False  False  False           False           False             False
1916  False  False  False           False           False             False

      Humidity  Rainfall  Duration  Color
0        False     False     False  False
1        False     False     False  False
2        False     False     False  False
3        False     False     False  False
4        False     False     False  False
...        ...       ...       ...    ...
1912     False     False     False  False
1913     False     False     False  False
1914     False     False     False  False
1915     False     False     False  False
1916     False     False     False  False

[1917 rows x 10 columns]

Count of Null Values in Each Column:
year                0
Month               0
Day                 0
Mean_Windspeed      0
Wind_Direction      0
Mean_Tempurature    0
Humidity            0
Rainfall            0
Duration            0
Color               0
dtype: int64

In [54]:
# create data frame and check data types
df = pd.DataFrame(data)

# Check data types of columns
column_types = df.dtypes
print("Data Types of Columns:")
print(column_types)

Data Types of Columns:
year                  int64
Month                 int64
Day                   int64
Mean_Windspeed      float64
Wind_Direction        int64
Mean_Tempurature    float64
Humidity              int64
Rainfall             object
Duration              int64
Color                object
dtype: object

In [55]:
# Select numeric columns
numeric_columns = df.select_dtypes(include=['int', 'float'])

# Display numeric columns
print("Numeric Columns:")
print(numeric_columns)

Numeric Columns:
      year  Month  Day  Mean_Windspeed  Wind_Direction  Mean_Tempurature  \
0     2019      1    1            18.4             360              12.3
1     2019      1    2            16.5             350              13.5
2     2019      1    3             9.2             360              14.7
3     2019      1    4            14.4             320              17.9
4     2019      1    5            12.6             320              18.0
...    ...    ...  ...             ...             ...               ...
1912  2024      3   27            24.5              90              23.3
1913  2024      3   28            11.1              80              24.9
1914  2024      3   29             9.1             260              25.7
1915  2024      3   30            11.1             150              26.8
1916  2024      3   31            19.6             220              28.3

      Humidity  Duration
0           65         0
1           65         0
2           77         0
3           84         0
4           89         0
...        ...       ...
1912        75         0
1913        77         0
1914        77         0
1915        74         0
1916        74         0

[1917 rows x 8 columns]

In [56]:
# Convert 'Rainfall' column to numeric with coerce to turn strings into NaN
numeric_values = pd.to_numeric(df['Rainfall'], errors='coerce')

# Count the number of NaN values, which represent strings
num_strings = numeric_values.isna().sum()

print("Number of string values in 'Rainfall' column:", num_strings)

string_records = df[pd.to_numeric(df['Rainfall'], errors='coerce').isna()]
print("String records in 'Rainfall' column:")
print(string_records)

Number of string values in 'Rainfall' column: 385
String records in 'Rainfall' column:
      year  Month  Day  Mean_Windspeed  Wind_Direction  Mean_Tempurature  \
0     2019      1    1            18.4             360              12.3
1     2019      1    2            16.5             350              13.5
2     2019      1    3             9.2             360              14.7
4     2019      1    5            12.6             320              18.0
5     2019      1    6            14.9             330              17.7
...    ...    ...  ...             ...             ...               ...
1888  2024      3    3            14.9              80              16.6
1890  2024      3    5            19.7             200              25.8
1898  2024      3   13            25.2              90              20.2
1901  2024      3   16            16.8              70              22.2
1903  2024      3   18            15.1              80              22.1

      Humidity Rainfall  Duration  Color
0           65    Trace         0  Green
1           65    Trace         0  Green
2           77    Trace         0  Green
4           89    Trace         0  Green
5           79    Trace         0  Green
...        ...      ...       ...    ...
1888        75    Trace         0  Green
1890        77    Trace         0  Green
1898        60    Trace         0  Green
1901        81    Trace         0  Green
1903        85    Trace         0  Green

[385 rows x 10 columns]

In [57]:
# fill with previouse value fill missing values backward along columns
df['Rainfall'] = numeric_values.bfill(axis=0)

print("DataFrame with string records in 'Value' column replaced with 0:")
print(df)

DataFrame with string records in 'Value' column replaced with 0:
      year  Month  Day  Mean_Windspeed  Wind_Direction  Mean_Tempurature  \
0     2019      1    1            18.4             360              12.3
1     2019      1    2            16.5             350              13.5
2     2019      1    3             9.2             360              14.7
3     2019      1    4            14.4             320              17.9
4     2019      1    5            12.6             320              18.0
...    ...    ...  ...             ...             ...               ...
1912  2024      3   27            24.5              90              23.3
1913  2024      3   28            11.1              80              24.9
1914  2024      3   29             9.1             260              25.7
1915  2024      3   30            11.1             150              26.8
1916  2024      3   31            19.6             220              28.3

      Humidity  Rainfall  Duration  Color
0           65       0.3         0  Green
1           65       0.3         0  Green
2           77       0.3         0  Green
3           84       0.3         0  Green
4           89       0.0         0  Green
...        ...       ...       ...    ...
1912        75       0.0         0  Green
1913        77       0.0         0  Green
1914        77       0.0         0  Green
1915        74       0.0         0  Green
1916        74       0.0         0  Green

[1917 rows x 10 columns]

In [62]:
# Feature Engineering
# # convert Wanring color string values to numeric values

type = {'Green': 0, 'Amber': 1, 'Red': 2, 'Black': 3 }
df['Color'] = df['Color'].map(type)

print(df)

      year  Month  Day  Mean_Windspeed  Wind_Direction  Mean_Tempurature  \
0     2019      1    1            18.4             360              12.3
1     2019      1    2            16.5             350              13.5
2     2019      1    3             9.2             360              14.7
3     2019      1    4            14.4             320              17.9
4     2019      1    5            12.6             320              18.0
...    ...    ...  ...             ...             ...               ...
1912  2024      3   27            24.5              90              23.3
1913  2024      3   28            11.1              80              24.9
1914  2024      3   29             9.1             260              25.7
1915  2024      3   30            11.1             150              26.8
1916  2024      3   31            19.6             220              28.3

      Humidity  Rainfall  Duration  Color  Flood
0           65       0.3         0    NaN     20
1           65       0.3         0    NaN     20
2           77       0.3         0    NaN     20
3           84       0.3         0    NaN     20
4           89       0.0         0    NaN     20
...        ...       ...       ...    ...    ...
1912        75       0.0         0    NaN     20
1913        77       0.0         0    NaN     20
1914        77       0.0         0    NaN     20
1915        74       0.0         0    NaN     20
1916        74       0.0         0    NaN     20

[1917 rows x 11 columns]

In [63]:
# Add a colunm to save flood forcast % based on the warning type
type = {0: 20, 1: 40, 2: 60, 3: 80 }
df['Flood'] = df['Color'].map(type)

print(df)

      year  Month  Day  Mean_Windspeed  Wind_Direction  Mean_Tempurature  \
0     2019      1    1            18.4             360              12.3
1     2019      1    2            16.5             350              13.5
2     2019      1    3             9.2             360              14.7
3     2019      1    4            14.4             320              17.9
4     2019      1    5            12.6             320              18.0
...    ...    ...  ...             ...             ...               ...
1912  2024      3   27            24.5              90              23.3
1913  2024      3   28            11.1              80              24.9
1914  2024      3   29             9.1             260              25.7
1915  2024      3   30            11.1             150              26.8
1916  2024      3   31            19.6             220              28.3

      Humidity  Rainfall  Duration  Color  Flood
0           65       0.3         0    NaN    NaN
1           65       0.3         0    NaN    NaN
2           77       0.3         0    NaN    NaN
3           84       0.3         0    NaN    NaN
4           89       0.0         0    NaN    NaN
...        ...       ...       ...    ...    ...
1912        75       0.0         0    NaN    NaN
1913        77       0.0         0    NaN    NaN
1914        77       0.0         0    NaN    NaN
1915        74       0.0         0    NaN    NaN
1916        74       0.0         0    NaN    NaN

[1917 rows x 11 columns]

In [64]:
#Create date column
df['Date'] = df['Day'].astype(str) + '-' + df['Month'].astype(str) + '-' + df['year'].astype(str)

print(df)

      year  Month  Day  Mean_Windspeed  Wind_Direction  Mean_Tempurature  \
0     2019      1    1            18.4             360              12.3
1     2019      1    2            16.5             350              13.5
2     2019      1    3             9.2             360              14.7
3     2019      1    4            14.4             320              17.9
4     2019      1    5            12.6             320              18.0
...    ...    ...  ...             ...             ...               ...
1912  2024      3   27            24.5              90              23.3
1913  2024      3   28            11.1              80              24.9
1914  2024      3   29             9.1             260              25.7
1915  2024      3   30            11.1             150              26.8
1916  2024      3   31            19.6             220              28.3

      Humidity  Rainfall  Duration  Color  Flood       Date
0           65       0.3         0    NaN    NaN   1-1-2019
1           65       0.3         0    NaN    NaN   2-1-2019
2           77       0.3         0    NaN    NaN   3-1-2019
3           84       0.3         0    NaN    NaN   4-1-2019
4           89       0.0         0    NaN    NaN   5-1-2019
...        ...       ...       ...    ...    ...        ...
1912        75       0.0         0    NaN    NaN  27-3-2024
1913        77       0.0         0    NaN    NaN  28-3-2024
1914        77       0.0         0    NaN    NaN  29-3-2024
1915        74       0.0         0    NaN    NaN  30-3-2024
1916        74       0.0         0    NaN    NaN  31-3-2024

[1917 rows x 12 columns]